"""
Django settings for at1 project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_p%hq(&whw(0f=gwt48om-*&qh^_5$ifaz4w*br^b4$(9rh^&#'

# SECURITY WARNING: don't run with debug turned on in production
ALLOWED_HOSTS = ['localhost', '127.0.0.1']

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py

...

ROOT_URLCONF = 'eduprod.urls'

...
